exports.validateMsg = {
  number: '请输入数字',
  positiveInteger: '请输入正整数',
  positiveIntegerLen1to5: '仅支持1~99999内的正整数',
  positiveIntegerMaxHour: '请输入0~876000内的整数',
  nonNegativeInteger: '请输入非负整数',
  positiveNumber: '请输入正数',
  nonNegativeNumber: '请输入非负数',
  phone: '请输入正确的手机号码',
  email: '请输入正确的邮箱',
  codeLen1to32: '请输入32个字符以内的数字、字母或下划线',
  usernameLen4to16: '请输入4-16个字符以内的数字或字母',
  usernameLen5to18: '请输入5-18个字符的数字、字母或_，必须以字母开头',
  passwordLen8to32: '至少1个大写字母，1个小写字母和1个数字，长度为8-32位',
  passwordLen8to32WithSymbol: `至少1个大写字母，1个小写字母和1个数字，可包含特殊符号，长度为8-32位`,
  passwordLen8to16WithSymbol: `至少1个大写字母，1个小写字母和1个数字，可包含特殊符号，长度为8-16位`,
  idCard: '请输入正确的身份证号码',
  percentage2Decimal: '请输入0-100，保留两位小数',
  percentagePositive: '请输入100以内的正整数',
  percentagePositiveN0: '请输入0-100的整数',
  max1Decimal: '请保留一位小数',
  max2Decimal: '请保留两位小数',
  max8IntN2Decimal: '最多输入8位整数，2位小数',
  chineseNumbersOrLetters: '请输入中文、数字或字母',
  postcode: '请输入正确的邮编',
  letterOrNumber: '请输入字母或数字',
  ipv4: '格式错误',
  ipv4Subnet: '格式错误',
  SSHSecretKeyLen2to64: '请输入正确的密钥名称',
  normalUrl: '请输入合法的地址',
  netName: '名称应以大写字母或小写字母开头，最长为128字符，且只包含“0-9, a-z, A-Z, "\'-_()[].:^”'
}
